apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-volume
spec:
  storageClassName: ""
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/malcolm/tmp/data/grafana"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: loki-volume
spec:
  storageClassName: ""
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/malcolm/tmp/data/loki"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-volume-claim
  namespace: grafana
spec:
  storageClassName: ""
  volumeName: grafana-volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-volume-claim
  namespace: grafana
spec:
  storageClassName: ""
  volumeName: loki-volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
