apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-volume
spec:
  storageClassName: local-storage
  local:
    path: /run/desktop/mnt/host/c/temp/data/grafana
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - docker-desktop
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-volume-claim
  namespace: grafana
spec:
  storageClassName: local-storage
  volumeName: grafana-volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi