---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: imageapi
  labels:
    appname: imageapi
spec:
  replicas: 1
  selector:
    matchLabels:
      appname: imageapi
  template:
    metadata:
      labels:
        appname: imageapi
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: /actuator/prometheus
    spec:
      containers:
        - name: imageapi
          image: malcolmpereira/imageapi:1.1.0
          imagePullPolicy: Always
          command: ["java"]
          args:
            [
              "-server",
              "-cp",
              "@/app/jib-classpath-file",
              "com.malcolm.imageapi.ImageAPIApp",
            ]
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "500Mi"
              cpu: "250m"
            limits:
              memory: "756Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 180
            periodSeconds: 10
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: imageapi
  labels:
    appname: imageapi
spec:
  selector:
    appname: imageapi
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: imageapi-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-body-size: "300m"
    nginx.ingress.kubernetes.io/ssl-passthrough: "false"
spec:
  tls:
    - hosts:
        - imageapi.malcolm.io
      secretName: imageapi-ingress-tls
  rules:
    - host: imageapi.malcolm.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: imageapi
                port:
                  number: 8080
