resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 750m
    memory: 750Mi
persistence:
  enabled: true
  type: pvc
  accessModes:
    - ReadWriteOnce
  existingClaim: loki-volume-claim
config:
  auth_enabled: true
