auth_enabled: true

loki:
  commonConfig:
    replication_factor: 1

  persistence:
    enabled: true
    type: pvc
    accessModes:
      - ReadWriteOnce
    existingClaim: loki-volume-claim  

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 750m
    memory: 750Mi

analytics:
  reporting_enabled: false

test:
  enabled: false

monitoring:
  selfMonitoring:
      enabled: false
      grafanaAgent:
        installOperator: false

  serviceMonitor:
      enabled: false
      metricsInstance:
        enabled: false    

  lokiCanary:
      enabled: false       
