loki:
  auth_enabled: true  
  commonConfig:
    replication_factor: 1
  storage:
    type: filesystem
    filesystem:
      chunks_directory: /var/loki/chunks
      rules_directory: /var/loki/rules
test:
  enabled: false	  

monitoring:
  dashboards:
    enabled: false
  rules: 
    enabled: false 
    alerting: false
  serviceMonitor:
    enabled: false
    metricsInstance:
      enabled: false     
  selfMonitoring:
    enabled: false
    grafanaAgent:
      installOperator: false
  lokiCanary:
      enabled: false

analytics:
  reporting_enabled: false

singleBinary:
  replicas: 1
  persistence:
    enabled: true
    size: 5Gi

Resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 750m
    memory: 750Mi
